version: '3.8'

services:
  agent:
    build: .
    container_name: agent
    devices:
      - /dev/gpiomem:/dev/gpiomem
      - /dev:/dev
    privileged: true
    cap_add:
      - SYS_RAWIO
    environment:
      XMPP_SERVER: "prosody"
      XMPP_PORT: 5222
      XMPP_DOMAIN: "prosody"
      XMPP_USERNAME: ${ROBOT_NAME}
      XMPP_PASSWORD: "top_secret"
      PYTHONUNBUFFERED: 1
    volumes:
      - ./agent:/agent
      - /run/udev:/run/udev:ro
      - /sys:/
      - ./images:/images
    extra_hosts:
      - "prosody:192.168.88.253"
