services:
  agent:
    build: .
    container_name: agent
    privileged: true
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/video0:/dev/video0
      - /dev/vchiq:/dev/vchiq
    environment:
      XMPP_SERVER: "prosody"
      XMPP_PORT: 5222
      XMPP_DOMAIN: "prosody"
      XMPP_USERNAME: "robot1"
      XMPP_PASSWORD: "top_secret"
      ROBOT_ID: "robot1"
      PYTHONUNBUFFERED: 1
    volumes:
      - ./agent:/app/agent
    extra_hosts:
      - "prosody:192.168.88.253"
