services:
  agent:
    build: .
    container_name: agent
    devices:
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    cap_add:
      - SYS_RAWIO
    environment:
      XMPP_SERVER: "prosody"
      XMPP_PORT: 5222
      XMPP_DOMAIN: "prosody"
      XMPP_USERNAME: "robot1"
      XMPP_PASSWORD: "top_secret"
      PYTHONUNBUFFERED: 1
      ROBOT_ID: "robot1"
      REDIS_HOST: "192.168.88.249"
      REDIS_PORT: "6379"
    volumes:
      - ./agent:/app/agent
    extra_hosts:
      - "prosody:192.168.88.253"
